#! /bin/sh

bspc monitor DVI-D-0 -n " " -d $(echo -e '\uf10c') $(echo -e '\uf10c') $(echo -e '\uf10c') $(echo -e '\uf10c') $(echo -e '\uf10c')
bspc monitor DVI-I-0 -n " " -d $(echo -e '\uf10c') $(echo -e '\uf10c') $(echo -e '\uf10c') $(echo -e '\uf10c') $(echo -e '\uf10c')

bspc config border_width        3
bspc config window_gap          18
bspc config top_padding      	15

# Autofocus window
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Border colors
bspc config focused_border_color "#72706e"
bspc config normal_border_color "#191918"
bspc config presel_feedback_color "#474542"

#xrandr --dpi 96

# Rules
bspc rule -a Gimp state=floating

# Autostart
redshift &
feh --bg-fill /home/brian/Bilder/PF.jpg &
pulseaudio --start 
compton --config ~/.config/compton.conf &
panel &
